### ISSUE TITLE
params not define

### ISSUE THREAD

**Issue by bigmushroom1** [Tebmer/SNRI#1]
line 406, in get_subgraphs
    nodes, node_labels = subgraph_extraction_labeling((head, tail), rel, adj_list, h=params_.hop, enclosing_sub_graph=params.enclosing_sub_graph, max_node_label_value=max_node_label_value)
NameError: name 'params' is not defined

**Comment by Tebmer** [comment]
Thanks for your input. The code can run successfully in my environment. You might want to consider changing "params" to "params_" and see if that resolves the issue. 

Feel free to reach out if you encounter any further difficulties.

**Comment by bigmushroom1** [comment]
Thank you for solving the above problem for me, but I found another bug during runtime:
Traceback (most recent call last):

  File "C:\Users\GUYUE\.conda\envs\py3.7\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\GUYUE\Desktop\SNRI-main\test_ranking.py", line 449, in get_rank
    head_scores = model_(data).squeeze(1).detach().numpy()
  File "C:\Users\GUYUE\.conda\envs\py3.7\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\GUYUE\Desktop\SNRI-main\model\dgl\graph_classifier.py", line 180, in forward
    graph_sizes = g.batch_num_nodes()
TypeError: 'list' object is not callable
Would it be convenient for you to answer for me?


| |
胡峥
|
|
***@***.***
|
---- Replied Message ----
| From | Shawn ***@***.***> |
| Date | 3/20/2024 13:57 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Tebmer/SNRI] params not define (Issue #1) |

Thanks for your input. The code can run successfully in my environment. You might want to consider changing "params" to "params_" and see if that resolves the issue.

Feel free to reach out if you encounter any further difficulties.
